
CFLAGS  += -mcmodel=medany -I${src_tree}/arch/${ARCH}/include
ASFLAGS += -I${src_tree}/arch/${ARCH}/include
LDFLAGS += -T ${src_tree}/arch/${ARCH}/riscv.lds
BOARD_TARGET := ${src_tree}/arch/${ARCH}/Image
export BOARD_TARGET

PHONY += board_compile
board_compile: kconfig_sync generate_asm hosttool_compile
	$Q${MAKE} -C ${src_tree}/arch/${ARCH} -f ${src_tree}/arch/${ARCH}/scripts/Makefile
