#ifndef __RISCV_ASM_PGFRAME_H
#define __RISCV_ASM_PGFRAME_H

#include <mm/kernel_map.h>

#define __ARCH_PGFRAME_PA_START 	RISCV_KERNEL_PA_START

#define __ARCH_PGFRAME_VA_START 	RISCV_KERNEL_VA_START

#define __ARCH_PGFRAME_SIZE 		((size_t)(RISCV_MEMORY_PA_END - RISCV_KERNEL_PA_START))

#define __ARCH_PGFRAME_PA_KSTART 	RISCV_KERNEL_PA_START

#define __ARCH_PGFRAME_FREE_VA_START	RISCV_FREE_VA_START

#define __ARCH_PGFRAME_FREE_SIZE	RISCV_FREE_SIZE

#endif /* __RISCV_ASM_PGFRAME_H */
