include ${src_tree}/scripts/Makefile.include
-include ${KCONFIG_AUTOCONF}

clean: clean_dtb clean_image
	@
ifneq ("${CONFIG_DTS_PATH}","")

quiet_cmd_cleandtb	= CLEAN DTB
cmd_cleandtb		= ${RM} ${CONFIG_DTS_PATH}/device.dtb
clean_dtb:
	$(call cmd,cleandtb)

else
clean_dtb:
	@
endif

quiet_cmd_cleanimage	= CLEAN BOARD_IMAGE
cmd_cleanimage		= ${RM} ${BOARD_TARGET}
clean_image:
	$(call cmd,cleanimage)
distclean:
	@

.PHONY: clean clean_dtb clean_image distclean
